export type Artist = {
  id: string;
  slug: string;
  name: string;
  name_ko?: string;
  bio: string;
  bio_ko: string;
  photo: string;
  photoFilter?: string;
  instagram?: string;
  youtube?: string;
  statement?: string;
  statement_ko?: string;
  artworkCount: number;
  worksGrid?: 2;
  worksLayout?: 'portrait3-mixed';
  medium?: string;
};

export type Artwork = {
  id: string;
  title: string;
  title_ko: string;
  description: string;
  description_ko: string;
  price: number;
  category: "painting" | "photo" | "craft";
  images: string[];
  artistId: string;
  artistName: string;
  stock: number;
  isSold: boolean;
  year: number;
  medium?: string;
  dimensions?: string;
  orientation?: 'portrait' | 'landscape' | 'square';
  priceDisplay?: string;
  series?: string;
  emotions?: string[];
  artistStatement?: string;
};

export const artists: Artist[] = [
  {
    id: "a1",
    slug: "betty-moon",
    name: "Betty Moon",
    name_ko: "베티문 베티 문유경",
    bio: "I believe that a unique energy flows through all things. Therefore, when taking a photograph, I first wait for that quiet moment of communion with the object's energy. It is that brief instant when the texture of the air subtly shifts, and light and color organically change their direction. Only then does the connection with the object begin. The warm eye contact a horse silently offered me when I lifted my head on a Jeju Oreum. The single, gentle light waiting for me amidst the sunset when I returned to a remote lodge in the California desert. And those scenes that halted me as the flow of the air instantaneously changed. I follow these subtle signals of change, pressing the shutter hundreds of times. And finally, I arrive at that one single frame where both our moods are perfectly superimposed. Ultimately, photography is the act of capturing the moment when my senses and the world's senses most naturally communicate and resonate.",
    bio_ko: "나는 모든 사물에 고유한 에너지가 흐른다고 믿는다. 그래서 사진을 찍을 때, 먼저 그 에너지와 조용히 교감하는 순간을 기다린다. 공기의 결이 부드럽게 바뀌고, 빛과 색이 스스로 방향을 틀어가는 아주 짧은 순간 — 그때 비로소 대상과의 연결이 시작된다. 제주 오름에서 고개를 들었을 때 말 한 마리가 아무 말 없이 건네던 따뜻한 눈맞춤. 캘리포니아 사막에서, 인적이 드문 숙소로 돌아왔을 때 석양 사이로 기다리던 한 줄기의 따뜻한 불빛. 그리고 공기의 흐름이 순간적으로 바뀌며 나를 멈춰 세웠던 그 장면들. 나는 이런 미세한 변화의 신호를 따라 수백 번 셔터를 누른다. 그리고 마침내 서로의 무드가 완전히 포개지는 단 하나의 장면에 다다른다. 사진은 결국, 나와 세계의 감각이 가장 자연스럽게 교감하는 순간을 붙잡는 일이다.",
    photo: "/artists/betty-moon.jpg",
    instagram: "@bettymoon_art",
    youtube: "https://www.youtube.com/@bettymoonstudio",
    artworkCount: 6,
    worksGrid: 2,
    medium: "photography",
  },
  {
    id: "a2",
    slug: "uiyeong-park",
    name: "Uiyeong Park",
    name_ko: "박의영 의영",
    bio: "My residency in Normandy, France became the starting point for my attention to the region's traditional stripe patterns. I regard these patterns not as mere decoration, but as cultural markers shaped by accumulated time and place, and I adopt them as the structural core of my work. Through variations in color, shifts in line thickness, and asymmetrical arrangements, I construct rhythm and tension within the canvas, placing Blue at its center. For me, Blue embodies both stillness and solitude, evoking contemplation while forming a sensory field in which I explore my inner self. The stripe does not emerge from repetition, but from a question about boundaries. By adjusting the intervals and directions of lines, I intentionally unsettle fixed orders and balances. These formal decisions stem from a reflection on the invisible boundaries between self and other, past and present, individual and society.",
    bio_ko: "프랑스 노르망디 레지던시 경험은 지역의 전통적인 스트라이프 패턴에 주목하게 한 계기가 되었다. 나는 이 패턴을 단순한 장식이 아닌, 시간과 장소가 축적된 문화적 표식으로 바라보며 작업의 핵심 구조로 삼았다. 색의 변화와 선의 굵기, 비대칭적 배열을 통해 화면에 리듬과 긴장을 형성하고, 그 중심에 블루를 배치했다. 블루는 평온과 고독, 사유의 감정을 동시에 내포하며 내면을 탐색하는 감각적 장을 만든다. 스트라이프는 반복이 아니라 경계에 대한 질문에서 출발하며, 나는 선의 간격과 방향을 조정해 고정된 질서를 흔든다. 이러한 조형적 선택은 자아와 타자, 과거와 현재, 개인과 사회 사이의 보이지 않는 경계를 사유하는 과정이다. 서로 다른 재료와 다층적 구조를 통해 감정과 사고의 여러 층위를 드러내고, 긴장 속 공존의 가능성을 탐색한다. 이 작업은 어딘가에 속하고자 하는 안정과 틀을 벗어나고자 하는 욕망 사이에서 균형을 모색하는, 여전히 진행 중인 질문에 대한 응답이다.",
    photo: "/artists/uiyeong-park.jpg",
    instagram: "@ui_yeong_park",
    artworkCount: 10,
    medium: "painting",
  },
  {
    id: "a4",
    slug: "harin-j",
    name: "Harin J",
    name_ko: "제은숙 하린",
    bio: "My work is a process of reconstructing on canvas the trajectory of 'Difference', a path endlessly deferred and unsettled between presence and absence. The texture of memory, the density of emotion, and the afterglow of light are not fixed entities but traces that continually slip away and transform. For me, abstraction is neither a rule nor a limitation aimed at formal completion, but a vessel that embraces the indefinable fragments of life and truth of vanishing moments. Ultimately, my practice moves beyond constrained form to create a new field where what is fading may finally dwell. Within this space of warm hospitality toward the disappearing, we are invited to encounter our own authentic landscapes.",
    bio_ko: "나의 작업은 현시(Presence)와 부재(Absence) 사이에 끊임없이 미뤄지고 흔들리는 '차연(Difference)'의 궤적을 화면위에 재구성하는 과정이다. 캔버스 위에 새겨진 기억의 결, 감정의 밀도, 빛의 잔향은 고정된 실체가 아니라 미끄러지고 변화하는 흔적들이다. 나에게 추상이란 형식의 완결을 지향하는 규칙이나 제한이 아니라, 규정할 수 없는 삶의 파편들과 사라져가는 순간의 진실을 수용하는 '그릇'이다. 결국 나의 작업은 얽매인 형식에서 벗어나 소멸하는 것들이 비로소 머물 수 있는 새로운 장(Field)을 마련하는 일이며, 사라져가는 것들을 향한 이 따뜻한 환대의 공간 안에서 우리는 비로소 각자의 진실한 정경과 마주하게 된다.",
    photo: "/artists/harin-j.jpg",
    artworkCount: 5,
    worksLayout: 'portrait3-mixed',
    medium: "painting",
  },
  {
    id: "a5",
    slug: "sung-eun-park",
    name: "Sung Eun Park",
    name_ko: "박성은",
    bio: "The 'Golden Horse' series embodies the ultimate form of spiritual freedom that artist Sung Eun Park has long explored. To the artist, the horse is not merely a creature that runs, but a symbol of the self and a totem of liberation. The golden horse in this series no longer treads upon the earth; instead, it floats as if swimming across traditional landscape paintings, expressing the boundless freedom of a weightless existence. The horse in the artwork has transcended desire and fear, reaching a state of enlightenment where it accepts itself just as it is. The pure gold adorning its body symbolizes an unchanging inner resolve and self-esteem, revealing the innate power of simply existing, without the need to race toward any specific destination. 'Golden Horse' is the culmination of the artist's spiritual journey. Originating from the core of the self, this journey transcends the boundaries of reality and fantasy, navigating through time and landscapes, scars and dreams, ultimately expanding into a modern mythos.",
    bio_ko: "'Golden Horse' 시리즈는 작가 박성은이 오랜 시간 탐구해온 정신적 자유의 궁극적인 형상을 담고 있다. 작가에게 말(馬)은 단지 달리는 존재가 아니라, 자아의 상징이자 해방의 토템이다. 이 시리즈에 등장하는 금빛 말은 더 이상 땅을 딛지 않고, 산수화 위를 유영하듯 부유하며 무게감 없는 존재의 자유로움을 표현한다. 작품 속 말은 욕망과 두려움을 지나, 자기 자신을 있는 그대로 받아들이는 깨달음의 상태에 이르러 있다. 그 몸에 입혀진 순금의 색은 변하지 않는 내면의 결의와 자존감을 상징하며, 어디론가 향하지 않아도 충분한 존재 그 자체의 힘을 드러낸다. 'Golden Horse'는 자아의 중심에서 출발한 작가의 정신적 여정이 현실과 환상의 경계를 넘어 시간과 풍경, 상처와 꿈을 통과하며 현대적인 신화(Mythos)로 확장된 결과물이다.",
    photo: "/artists/sung-eun-park.jpg",
    artworkCount: 6,
    medium: "painting",
  },
  {
    id: "a6",
    slug: "byeong-gwan-seo",
    name: "Byeong Gwan Seo",
    name_ko: "서병관",
    bio: "Byeong Gwan Seo explores structure and absence through sculpture and spatial practice.",
    bio_ko: "서병관은 조각과 공간 실천을 통해 구조와 부재를 탐구합니다.",
    photo: "/artists/byeong-gwan-seo.jpg",
    artworkCount: 0,
    medium: "sculpture",
  },
  {
    id: "a7",
    slug: "jae-eun-jeong",
    name: "Jae Eun Jeong",
    name_ko: "정재은",
    bio: "Jae Eun Jeong's paintings hold suspended time — moments caught between breath and stillness.",
    bio_ko: "정재은의 회화는 정지된 시간을 품습니다 — 숨과 고요 사이에 포착된 순간들.",
    photo: "/artists/jae-eun-jeong.jpg",
    statement: "I seek to restore the sense of place—which is easily lost to economic logic—into a space for artistic contemplation that transcends physical boundaries, using the fundamental elements of painting and architectural imagery. The lines, color fields, and multi-layered strata constructed on the canvas form strata where memories of the past collide with the reality of the present. I wish to shatter the fixed visual frame through this \"interval\" between invisible memory and visible form, awaken a floating sensation of multiple perspectives, and allow viewers to experience the freedom of subjective thought that drifts freely.",
    statement_ko: "경제적 논리로 쉽게 상실되어가는 장소의 감각을 회화의 기본 요소와 건축적 이미지를 통해 물리적 경계를 넘어선 예술적 사유의 공간으로 복원하고자 한다. 캔버스 위에 구축된 선과 색면, 다층의 층위들은 과거의 기억과 현재의 실재가 충돌하는 지층이다. 이 보이지 않는 기억과 보이는 형태 사이의 '간격(Interval)'은 고정된 시각적 프레임을 깨부수고 다중 시점의 부유하는 감각을 일깨우고 자유롭게 유영하는 주체적 사유의 자유를 경험하게 하고 싶다.",
    instagram: "@jeongjaeeun1012",
    artworkCount: 16,
    medium: "painting",
  },
  {
    id: "a8",
    slug: "young-jae-lee",
    name: "Young Jae Lee",
    name_ko: "이영재",
    bio: "Young Jae Lee works with glass casting, coaxing light into form. Each piece begins as molten material and emerges as something caught between solid and translucent — an object that holds stillness while seeming on the verge of dissolving. Her works are vessels of time: moments solidified in glass, named after the quiet hours and seasons that shaped them.",
    bio_ko: "이영재는 유리 주조(glass casting) 작업을 한다. 녹아 있는 재료에서 출발해, 고체와 투명 사이 어딘가에 존재하는 형태를 끌어낸다. 그의 작품은 시간의 그릇이다 — 고요한 시간과 계절이 유리 속에 응고된, 사라지기 직전의 순간들.",
    photo: "/artists/young-jae-lee.png",
    photoFilter: "grayscale(100%)",
    artworkCount: 8,
    medium: "glass",
  },
];

export const artworks: Artwork[] = [
  {
    id: "w37",
    title: "My October",
    title_ko: "My October",
    description: "Oil on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/harin-j/my-october.jpg"],
    artistId: "a4",
    artistName: "Harin J",
    stock: 0,
    isSold: true,
    year: 2025,
    medium: "Oil on Canvas",
    dimensions: "45 × 53 cm",
    emotions: ["nostalgia", "stillness", "memory"],
    artistStatement: "October holds a particular quality of light — the kind that makes you feel something is ending and beginning at once.",
  },
  {
    id: "w38",
    title: "Green-Stained Memories",
    title_ko: "Green-Stained Memories",
    description: "Oil on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/harin-j/green-stained-memories.jpg"],
    artistId: "a4",
    artistName: "Harin J",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Oil on Canvas",
    dimensions: "60.6 × 50 cm",
    priceDisplay: "$2,000",
    orientation: "landscape",
    emotions: ["memory", "longing", "warmth"],
    artistStatement: "Memories bleed into one another like pigment on wet canvas. This work is about that stain — the way the past colors everything we see.",
  },
  {
    id: "w39",
    title: "Inner land scape",
    title_ko: "Inner land scape",
    description: "Oil, charcoal on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/harin-j/inner-landscape.jpg"],
    artistId: "a4",
    artistName: "Harin J",
    stock: 0,
    isSold: true,
    year: 2025,
    medium: "Oil, charcoal on Canvas",
    dimensions: "53 × 53 cm",
    priceDisplay: "$900",
    orientation: "square",
    emotions: ["introspection", "tension", "depth"],
    artistStatement: "The inner landscape is not a place you visit — it is where you already are, always.",
  },
  {
    id: "w40",
    title: "Memory",
    title_ko: "Memory",
    description: "Oil on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/harin-j/memory.jpg"],
    artistId: "a4",
    artistName: "Harin J",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Oil on Canvas",
    dimensions: "53 × 65.2 cm",
    priceDisplay: "문의",
    emotions: ["memory", "absence", "longing"],
    artistStatement: "Memory is not what happened. It is what remains after everything else has dissolved.",
  },
  {
    id: "w41",
    title: "Spring Field",
    title_ko: "Spring Field",
    description: "Acrylic on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/harin-j/spring-field.jpg"],
    artistId: "a4",
    artistName: "Harin J",
    stock: 1,
    isSold: false,
    year: 2023,
    medium: "Acrylic on Canvas",
    dimensions: "60.6 × 72.7 cm",
    priceDisplay: "$3,500",
    emotions: ["renewal", "joy", "openness"],
    artistStatement: "Spring arrives not as an event but as a permission — to begin again, to expand, to be seen.",
  },
  {
    id: "w34",
    title: "Invite into the New World",
    title_ko: "새로운 세계로의 초대",
    description: "An invitation rendered in Korean traditional pigments and 24k gold leaf on Hanji. A threshold between the familiar and the unknown.",
    description_ko: "한국 전통 안료와 24k 금박, 한지 위에 담긴 초대. 익숙함과 낯섦 사이의 경계.",
    price: 4000000,
    category: "painting",
    images: ["/artworks/sung-eun-park/invite-into-the-new-world.jpg"],
    artistId: "a5",
    artistName: "Sung Eun Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Korean pigment, 24k gold leaf, Hanji",
    dimensions: "60.6 × 60.6 cm",
    orientation: "square",
    emotions: ["freedom", "transcendence", "luminous"],
    artistStatement: "Every threshold holds a question. This work is the moment before the answer — suspended, golden, weightless.",
  },
  {
    id: "w35",
    title: "Invite into a New World G",
    title_ko: "새로운 세계로의 초대 G",
    description: "A gold-inflected variation on the threshold motif. 24k gold leaf dominates the surface, drawing the viewer into an luminous beyond.",
    description_ko: "경계의 모티프를 금빛으로 변주한 작품. 24k 금박이 화면을 가득 채우며 찬란한 너머로 이끕니다.",
    price: 4000000,
    category: "painting",
    images: ["/artworks/sung-eun-park/invite-into-a-new-world-g.jpg"],
    artistId: "a5",
    artistName: "Sung Eun Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Korean pigment, 24k gold leaf, Hanji",
    dimensions: "60.6 × 60.6 cm",
    orientation: "square",
    emotions: ["luminous", "transcendence", "spirituality"],
    artistStatement: "Gold has always been the color of what we cannot hold — the divine, the sacred, the unreachable. This is an invitation to step closer anyway.",
  },
  {
    id: "w36",
    title: "The Moment We Met II",
    title_ko: "우리가 만난 순간 II",
    description: "A more intimate version of the encounter — smaller in scale, quieter in tone, yet no less charged with stillness.",
    description_ko: "만남의 더 작고 조용한 버전. 크기는 줄었지만 고요함의 밀도는 그대로입니다.",
    price: 2000000,
    category: "painting",
    images: ["/artworks/sung-eun-park/the-moment-we-met-ii.jpg"],
    artistId: "a5",
    artistName: "Sung Eun Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Korean pigment, 24k gold leaf, Hanji",
    dimensions: "45 × 45 cm",
    orientation: "square",
    emotions: ["stillness", "connection", "intimacy"],
    artistStatement: "Some meetings happen in silence. This is that silence — held, gilded, and made permanent.",
  },
  {
    id: "w13",
    title: "Golden Cheonma",
    title_ko: "황금 천마",
    description: "A mythical horse rendered in Korean traditional pigments and 24k gold leaf on Hanji. The celestial steed moves through a field of pure gold.",
    description_ko: "한국 전통 안료와 24k 금박, 한지 위에 그려진 신화 속 천마. 황금빛 화면을 가로지르는 하늘의 말.",
    price: 4000000,
    category: "painting",
    images: ["/artworks/sung-eun-park/golden-cheonma.jpg"],
    artistId: "a5",
    artistName: "Sung Eun Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Korean pigment, 24k gold leaf, Hanji",
    dimensions: "60.6 × 60.6 cm",
    orientation: "square",
    emotions: ["freedom", "mythology", "power"],
    artistStatement: "The celestial horse does not run — it floats. This is what freedom looks like when it no longer needs the ground.",
  },
  {
    id: "w15",
    title: "The Moment We Met",
    title_ko: "우리가 만난 순간",
    description: "A square composition marking the stillness of a first encounter. Gold leaf catches the light like memory catching time.",
    description_ko: "처음 만남의 고요함을 담은 정방형 작품. 금박은 기억이 시간을 붙잡듯 빛을 포착합니다.",
    price: 6000000,
    category: "painting",
    images: ["/artworks/sung-eun-park/the-moment-we-met.jpg"],
    artistId: "a5",
    artistName: "Sung Eun Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Korean pigment, 24k gold leaf, Hanji",
    dimensions: "72.7 × 72.7 cm",
    orientation: "square",
    emotions: ["connection", "wonder", "stillness"],
    artistStatement: "The first moment of genuine encounter leaves something behind — a residue of light that no explanation can dissolve.",
  },
  {
    id: "w14",
    title: "Golden Freedom",
    title_ko: "황금 자유",
    description: "A large-scale work exploring the tension between confinement and flight. Korean pigments and gold leaf create a luminous surface that shifts with the light.",
    description_ko: "구속과 비상 사이의 긴장을 탐구하는 대형 작품. 한국 안료와 금박이 빛에 따라 변하는 찬란한 표면을 만들어냅니다.",
    price: 16000000,
    category: "painting",
    images: ["/artworks/sung-eun-park/golden-freedom.jpg"],
    artistId: "a5",
    artistName: "Sung Eun Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Korean pigment, 24k gold leaf, Hanji",
    dimensions: "145.5 × 97.0 cm",
    orientation: "landscape",
    emotions: ["freedom", "transcendence", "luminous"],
    artistStatement: "Freedom at this scale is not an escape — it is an arrival. The horse arrives at itself.",
  },
  {
    id: "w25",
    title: "Light and Shadow",
    title_ko: "Light and Shadow",
    description: "Archival Pigment Print on Hahnemuhle Photo Rag Satin 310g Paper.",
    description_ko: "",
    price: 3000000,
    category: "photo",
    images: ["/artworks/betty-moon/light-and-shadow.jpg"],
    artistId: "a1",
    artistName: "Betty Moon",
    stock: 1,
    isSold: false,
    year: 2023,
    medium: "Archival Pigment Print on Hahnemuhle Photo Rag Satin 310g Paper",
    dimensions: "150 × 100 cm",
    orientation: "landscape",
    emotions: ["contrast", "calm", "presence"],
    artistStatement: "I waited three hours for this light. It arrived for less than a minute. That minute is this photograph.",
  },
  {
    id: "w23",
    title: "Mother Nature",
    title_ko: "Mother Nature",
    description: "Archival Pigment Print on Hahnemuhle Photo Rag Satin 310g Paper.",
    description_ko: "",
    price: 3000000,
    category: "photo",
    images: ["/artworks/betty-moon/mother-nature.jpg"],
    artistId: "a1",
    artistName: "Betty Moon",
    stock: 1,
    isSold: false,
    year: 2023,
    medium: "Archival Pigment Print on Hahnemuhle Photo Rag Satin 310g Paper",
    dimensions: "150 × 100 cm",
    orientation: "landscape",
    emotions: ["awe", "connection", "vastness"],
    artistStatement: "Nature doesn't perform for the camera. You have to become quiet enough that it forgets you're there.",
  },
  {
    id: "w24",
    title: "Arrival",
    title_ko: "Arrival",
    description: "Archival Pigment Print on Korean Traditional Paper (Hanji).",
    description_ko: "",
    price: 2000000,
    category: "photo",
    images: ["/artworks/betty-moon/arrival.jpg"],
    artistId: "a1",
    artistName: "Betty Moon",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Archival Pigment Print on Korean Traditional Paper (Hanji)",
    dimensions: "60 × 90 cm",
    orientation: "landscape",
    emotions: ["anticipation", "warmth", "threshold"],
    artistStatement: "A single light waited for me in the California desert. It felt like a welcome. This is what belonging looks like.",
  },
  {
    id: "w27",
    title: "Table is Ready",
    title_ko: "Table is Ready",
    description: "Archival Pigment Print on Creamish Paper.",
    description_ko: "",
    price: 2000000,
    category: "photo",
    images: ["/artworks/betty-moon/table-is-ready.jpg"],
    artistId: "a1",
    artistName: "Betty Moon",
    stock: 1,
    isSold: false,
    year: 2020,
    medium: "Archival Pigment Print on Creamish Paper",
    dimensions: "90 × 52 cm",
    orientation: "landscape",
    emotions: ["intimacy", "warmth", "anticipation"],
    artistStatement: "Someone set this table with care, before anyone arrived. That act of preparation — for an unseen guest — is one of the most human things I know.",
  },
  {
    id: "w26",
    title: "Returning to Myself II",
    title_ko: "Returning to Myself II",
    description: "Archival Pigment Print on Korean Traditional Paper (Hanji).",
    description_ko: "",
    price: 2000000,
    category: "photo",
    images: ["/artworks/betty-moon/returning-to-myself-ii.jpg"],
    artistId: "a1",
    artistName: "Betty Moon",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Archival Pigment Print on Korean Traditional Paper (Hanji)",
    dimensions: "60 × 90 cm",
    emotions: ["solitude", "stillness", "renewal"],
    artistStatement: "Returning to yourself is not a dramatic event. It happens quietly, the way dawn replaces night — without announcement.",
  },
  {
    id: "w22",
    title: "Returning to Myself I",
    title_ko: "나 자신으로 돌아오며 I",
    description: "Archival Pigment Print on Korean Traditional Paper (Hanji).",
    description_ko: "한지에 아카이벌 피그먼트 프린트.",
    price: 3000000,
    category: "photo",
    images: ["/artworks/betty-moon/returning-to-myself-i.jpg"],
    artistId: "a1",
    artistName: "Betty Moon",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Archival Pigment Print on Korean Traditional Paper (Hanji)",
    dimensions: "120 × 80 cm",
    orientation: "landscape",
    emotions: ["solitude", "renewal", "calm"],
    artistStatement: "The horse on the Jeju Oreum looked at me without judgment. In that eye contact, I found something I had been looking for.",
  },
  {
    id: "w31",
    title: "The Wall and the Wait 1_2",
    title_ko: "The Wall and the Wait 1_2",
    description: "Acrylic on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/the-wall-and-the-wait-1-2.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Acrylic on Wooden Panel",
    dimensions: "60.5 × 60.5 cm",
    orientation: "square",
    series: "The Wall and The Wait",
    priceDisplay: "문의",
    emotions: ["tension", "boundary", "contemplation"],
    artistStatement: "The wall is not an obstacle. It is a question the line keeps asking — where do I end, and where do you begin?",
  },
  {
    id: "w66",
    title: "The Wall and the Wait 1_4",
    title_ko: "The Wall and the Wait 1_4",
    description: "Acrylic on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/the-wall-and-the-wait-1-4.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Acrylic on Wooden Panel",
    dimensions: "60.5 × 60.5 cm",
    orientation: "square",
    series: "The Wall and The Wait",
    priceDisplay: "문의",
  },
  {
    id: "w67",
    title: "The Wall and the Wait 1_5",
    title_ko: "The Wall and the Wait 1_5",
    description: "Acrylic on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/the-wall-and-the-wait-1-5.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Acrylic on Wooden Panel",
    dimensions: "60.5 × 60.5 cm",
    orientation: "square",
    series: "The Wall and The Wait",
    priceDisplay: "문의",
  },
  {
    id: "w68",
    title: "The Wall and the Wait 2_2",
    title_ko: "The Wall and the Wait 2_2",
    description: "Acrylic on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/the-wall-and-the-wait-2-2.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Acrylic on Wooden Panel",
    dimensions: "72.5 × 72.5 cm",
    orientation: "square",
    series: "The Wall and The Wait",
    priceDisplay: "문의",
  },
  {
    id: "w69",
    title: "The Wall and the Wait 2_3",
    title_ko: "The Wall and the Wait 2_3",
    description: "Acrylic on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/the-wall-and-the-wait-2-3.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Acrylic on Wooden Panel",
    dimensions: "72.5 × 72.5 cm",
    orientation: "square",
    series: "The Wall and The Wait",
    priceDisplay: "문의",
  },
  {
    id: "w29",
    title: "dam da 4_11",
    title_ko: "dam da 4_11",
    description: "Mixed Media on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/dam-da-4-11.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Mixed Media on Canvas",
    dimensions: "65 × 80 cm",
    orientation: "square",
    series: "dam da",
    emotions: ["rhythm", "depth", "introspection"],
    artistStatement: "'Dam da' — to contain, to hold. This work holds something I cannot name in any other way.",
  },
  {
    id: "w70",
    title: "dam da 2_2",
    title_ko: "dam da 2_2",
    description: "Mixed Media on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/dam-da-2-2.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Mixed Media on Wooden Panel",
    dimensions: "91 × 91 cm",
    orientation: "square",
    series: "dam da",
    priceDisplay: "문의",
  },
  {
    id: "w71",
    title: "dam da 3_1",
    title_ko: "dam da 3_1",
    description: "Mixed Media on Wooden Panel.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/dam-da-3-1.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Mixed Media on Wooden Panel",
    dimensions: "26 × 21 cm",
    orientation: "square",
    series: "dam da",
    priceDisplay: "문의",
  },
  {
    id: "w30",
    title: "contenir 4_10",
    title_ko: "contenir 4_10",
    description: "Acrylic on Canvas.",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/contenir-4-10.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Acrylic on Canvas",
    dimensions: "77 × 98 cm",
    series: "contenir",
    emotions: ["calm", "rhythm", "contemplation"],
    artistStatement: "To contain is not to suppress — it is to give shape to what would otherwise dissolve. Blue holds this.",
  },
  {
    id: "w28",
    title: "contenir 3_5",
    title_ko: "contenir 3_5",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/uiyeong-park/contenir-3-5.jpg"],
    artistId: "a2",
    artistName: "Uiyeong Park",
    stock: 0,
    isSold: false,
    year: 2025,
    medium: "Acrylic on Canvas",
    dimensions: "60.5 × 100 cm",
    series: "contenir",
    emotions: ["calm", "boundary", "contemplation"],
    artistStatement: "This series began in Normandy, where the stripes weren't decoration — they were the memory of borders crossed and recrossed.",
  },
  {
    id: "w42",
    title: "Dream 02",
    title_ko: "Dream 02",
    description: "Glass casting sculpture. A slender form suspended between solid and light.",
    description_ko: "유리 주조 조각. 고체와 빛 사이 어딘가에 정지된 가느다란 형태.",
    price: 1800000,
    category: "craft",
    images: [
      "/artworks/youngjae-lee/dream-02-front.jpg",
      "/artworks/youngjae-lee/dream-02-back.jpg",
      "/artworks/youngjae-lee/dream-02-detail.jpg",
    ],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Glass casting",
    dimensions: "36.5 × 8.5 × 6 cm",
    orientation: "landscape",
    emotions: ["stillness", "transparency", "fragility"],
    artistStatement: "Glass begins as molten chaos. What emerges is a question: what does a dream look like when it solidifies?",
  },
  {
    id: "w43",
    title: "Dream 04",
    title_ko: "Dream 04",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 1800000,
    category: "craft",
    images: [
      "/artworks/youngjae-lee/dream-04.jpg",
      "/artworks/youngjae-lee/dream-04-top.jpg",
    ],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 1,
    isSold: false,
    year: 2026,
    medium: "Glass casting",
    dimensions: "37 × 6 × 6 cm",
    orientation: "landscape",
    emotions: ["stillness", "transparency", "time"],
    artistStatement: "Each piece carries the memory of fire — the heat that shaped it — now held in permanent transparency.",
  },
  {
    id: "w44",
    title: "May 12",
    title_ko: "May 12",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 1200000,
    category: "craft",
    images: [
      "/artworks/youngjae-lee/may-12.jpg",
      "/artworks/youngjae-lee/may-12-detail.jpg",
    ],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 1,
    isSold: false,
    year: 2022,
    medium: "Glass casting",
    dimensions: "18 × 8 × 11 cm",
    orientation: "landscape",
    emotions: ["time", "memory", "stillness"],
    artistStatement: "A specific day. Glass holds it the way only objects can — without interpretation, without forgetting.",
  },
  {
    id: "w45",
    title: "afternoon",
    title_ko: "afternoon",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 800000,
    category: "craft",
    images: ["/artworks/youngjae-lee/afternoon-s.jpg"],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 0,
    isSold: true,
    year: 2023,
    medium: "Glass casting",
    dimensions: "13 × 18 × 6 cm",
    orientation: "landscape",
    emotions: ["calm", "time", "light"],
    artistStatement: "Afternoon light changes everything it touches. Glass holds that quality — the way things glow just before they fade.",
  },
  {
    id: "w46",
    title: "afternoon",
    title_ko: "afternoon",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 3200000,
    category: "craft",
    images: ["/artworks/youngjae-lee/afternoon-l.jpg"],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 0,
    isSold: true,
    year: 2023,
    medium: "Glass casting",
    dimensions: "23 × 11.5 × 27 cm",
    orientation: "landscape",
    emotions: ["calm", "time", "light"],
    artistStatement: "The larger form holds more silence. Size changes the quality of stillness.",
  },
  {
    id: "w47",
    title: "dawn",
    title_ko: "dawn",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 2200000,
    category: "craft",
    images: ["/artworks/youngjae-lee/dawn.jpg"],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 1,
    isSold: false,
    year: 2023,
    medium: "Glass casting",
    dimensions: "17 × 28 × 9 cm",
    orientation: "landscape",
    emotions: ["hope", "renewal", "transparency"],
    artistStatement: "Before anything is certain, there is this — light beginning to enter. Dawn is the most honest moment of any day.",
  },
  {
    id: "w48",
    title: "dreams 01",
    title_ko: "dreams 01",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 1600000,
    category: "craft",
    images: [
      "/artworks/youngjae-lee/dreams-01.jpg",
      "/artworks/youngjae-lee/dreams-01-detail.jpg",
    ],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Glass casting",
    dimensions: "36 × 5 × 5.5 cm",
    orientation: "landscape",
    emotions: ["fragility", "stillness", "transparency"],
    artistStatement: "Dreams are shapeless. Casting them in glass is the attempt to hold what cannot be held.",
  },
  {
    id: "w49",
    title: "hope",
    title_ko: "hope",
    description: "Glass casting sculpture.",
    description_ko: "유리 주조 조각.",
    price: 3200000,
    category: "craft",
    images: [
      "/artworks/youngjae-lee/hope-front.jpg",
      "/artworks/youngjae-lee/hope-back.jpg",
    ],
    artistId: "a8",
    artistName: "Young Jae Lee",
    stock: 1,
    isSold: false,
    year: 2023,
    medium: "Glass casting",
    dimensions: "26 × 15 × 7.5 cm",
    orientation: "portrait",
    emotions: ["hope", "luminous", "presence"],
    artistStatement: "Hope is not optimism — it is the decision to remain open. This form embodies that decision.",
  },
  {
    id: "w50",
    title: "Interval Arch 2",
    title_ko: "Interval Arch 2",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-arch-2.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2025,
    medium: "Mixed media on canvas",
    dimensions: "72.7 × 60.6 cm",
    series: "Interval",
  },
  {
    id: "w51",
    title: "Interval 21",
    title_ko: "Interval 21",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-21.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2006,
    medium: "Mixed media on canvas",
    dimensions: "140 × 180 cm",
    series: "Interval",
  },
  {
    id: "w52",
    title: "Interval 208",
    title_ko: "Interval 208",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-208.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2006,
    medium: "Mixed media on canvas",
    dimensions: "91 × 116.8 cm",
    series: "Interval",
  },
  {
    id: "w53",
    title: "Interval RE",
    title_ko: "Interval RE",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-re.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2022,
    medium: "Mixed media on canvas",
    dimensions: "162.2 × 130.3 cm",
    orientation: "landscape",
    series: "Interval",
  },
  {
    id: "w54",
    title: "Interval 501",
    title_ko: "Interval 501",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-501.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2020,
    medium: "Mixed media on canvas",
    dimensions: "162.2 × 130.3 cm",
    orientation: "landscape",
    series: "Interval",
  },
  {
    id: "w55",
    title: "Interval Step",
    title_ko: "Interval Step",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-step.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2020,
    medium: "Mixed media on canvas",
    dimensions: "37.9 × 45.5 cm",
    orientation: "landscape",
    series: "Interval",
  },
  {
    id: "w56",
    title: "Interval 18",
    title_ko: "Interval 18",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-18.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 0,
    medium: "Mixed media on canvas",
    dimensions: "72.7 × 53 cm",
    orientation: "landscape",
    series: "Interval",
  },
  {
    id: "w57",
    title: "Interval RE-s",
    title_ko: "Interval RE-s",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-re-s.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2022,
    medium: "Mixed media on canvas",
    dimensions: "D. 40 cm",
    orientation: "square",
    series: "Interval",
  },
  {
    id: "w58",
    title: "Interval 212",
    title_ko: "Interval 212",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-212.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2015,
    medium: "Mixed media on canvas",
    dimensions: "55 × 55 cm",
    orientation: "square",
    series: "Interval",
  },
  {
    id: "w59",
    title: "Interval 213",
    title_ko: "Interval 213",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/interval-213.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2015,
    medium: "Mixed media on canvas",
    dimensions: "55 × 55 cm",
    orientation: "square",
    series: "Interval",
  },
  {
    id: "w60",
    title: "Structure and Speed 03",
    title_ko: "구조와 속력으로 03",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/gws-03-f100.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2005,
    medium: "Mixed media on canvas",
    dimensions: "162.2 × 130.3 cm",
    series: "Structure and Speed",
  },
  {
    id: "w61",
    title: "Structure and Speed 72.7×90",
    title_ko: "구조와 속력으로 72.7×90",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/gws-72x90.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2012,
    medium: "Mixed media on canvas",
    dimensions: "72.7 × 90 cm",
    series: "Structure and Speed",
  },
  {
    id: "w62",
    title: "Structure and Speed 03 (Study)",
    title_ko: "구조와 속력으로 03 (소품)",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/gws-03-f6.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2005,
    medium: "Mixed media on canvas",
    dimensions: "40.9 × 31.8 cm",
    series: "Structure and Speed",
  },
  {
    id: "w63",
    title: "Structure and Speed 02",
    title_ko: "구조와 속력으로 02",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/gws-02.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2005,
    medium: "Mixed media on canvas",
    dimensions: "162.2 × 130.3 cm",
    orientation: "landscape",
    series: "Structure and Speed",
  },
  {
    id: "w64",
    title: "Structure and Speed 55×45",
    title_ko: "구조와 속력으로 55×45",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/gws-55x45.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2020,
    medium: "Mixed media on canvas",
    dimensions: "55 × 45 cm",
    orientation: "landscape",
    series: "Structure and Speed",
  },
  {
    id: "w65",
    title: "Structure and Speed 07",
    title_ko: "구조와 속력으로 07",
    description: "",
    description_ko: "",
    price: 0,
    category: "painting",
    images: ["/artworks/jae-eun-jeong/gws-07.jpg"],
    artistId: "a7",
    artistName: "Jae Eun Jeong",
    stock: 1,
    isSold: false,
    year: 2005,
    medium: "Mixed media on canvas",
    dimensions: "162.2 × 130.3 cm",
    orientation: "landscape",
    series: "Structure and Speed",
  },
];

export type ArtistVideo = {
  id: string;
  artistId: string;
  artistSlug: string;
  artistName: string;
  title: string;
  duration?: string;
  url: string;         // YouTube watch URL
  thumbnail?: string;  // 비유튜브 영상용 수동 오버라이드
  noEmbed?: boolean;   // true면 임베드 대신 YouTube 새 탭으로 열기
};

export const artistVideos: ArtistVideo[] = [
  {
    id: "v1",
    artistId: "a1",
    artistSlug: "betty-moon",
    artistName: "Betty Moon",
    title: "Mother Nature Exhibition",
    duration: "4:32",
    url: "https://www.youtube.com/watch?v=D83nSLLX00o",
  },
  {
    id: "v2",
    artistId: "a8",
    artistSlug: "young-jae-lee",
    artistName: "Young Jae Lee",
    title: "Young Jae Lee — Glass Artist",
    url: "https://youtu.be/4145YTRnG4E",
  },
  {
    id: "v3",
    artistId: "a5",
    artistSlug: "sung-eun-park",
    artistName: "Sung Eun Park",
    title: "Sung Eun Park",
    duration: "",
    url: "https://youtu.be/-Ldafm_vp88?si=ZVg74h3fDi3_YNbt",
  },
];

export type ArtFair = {
  id: string;
  name: string;
  venue: string;
  location: string;
  boothNumber?: string;
  artists: string[];
  previewDate?: string;
  startDate: string;
  endDate: string;
  status: "current" | "upcoming" | "past";
  coverImage: string;
  description?: string;
  artworkIds?: string[];
};

export const artFairs: ArtFair[] = [
  {
    id: "f9",
    name: "Positions Berlin Art Fair 2026",
    venue: "Flughafen Tempelhof, Hangar 5–6",
    location: "Berlin, Germany",
    artists: ["Betty Moon", "Uiyeong Park", "Harin J", "Ha Jeong Lim", "Byeong Gwan Seo"],
    startDate: "2026-09-10",
    endDate: "2026-09-13",
    status: "upcoming",
    coverImage: "/art-fairs/positions-berlin-2026/cover.png",
    description: "FOEM presents works by Betty Moon, Uiyeong Park, Harin J, Ha Jeong Lim, and Byeong Gwan Seo at Positions Berlin Art Fair 2026 — one of Europe's leading platforms for contemporary art.",
    artworkIds: ["w22", "w23", "w25", "w38", "w41", "w29", "w30"],
  },
  {
    id: "f5",
    name: "Affordable Art Fair Hong Kong 2026",
    venue: "Hong Kong Convention & Exhibition Centre",
    location: "Hong Kong",
    artists: ["Sung Eun Park"],
    previewDate: "2026-05-14",
    startDate: "2026-05-15",
    endDate: "2026-05-18",
    status: "past",
    coverImage: "/art-fairs/hong-kong-2026/affordable art fair.jpg",
    description: "Sung Eun Park presents works at the Affordable Art Fair Hong Kong 2026. VIP Preview May 14 (1pm–9:30pm) · May 15 (12pm–8:30pm) · May 16–17 (10am–8:30pm) · May 18 (10am–7pm).",
    artworkIds: ["w13", "w15", "w34", "w35", "w36"],
  },
  {
    id: "f7",
    name: "BANK Art Fair 2026 Spring",
    venue: "SETEC",
    location: "Seoul, Korea",
    artists: ["Sung Eun Park", "Young Jae Lee", "Insue Kim"],
    previewDate: "2026-04-30",
    startDate: "2026-04-30",
    endDate: "2026-05-03",
    status: "past",
    coverImage: "/art-fairs/bank-art-fair-2026-spring/bank art fair 2026.jpg",
  },
  {
    id: "f4",
    name: "ARTANKARA 2026",
    venue: "ATO Congresium",
    location: "Ankara, Turkey",
    artists: ["Betty Moon", "Uiyeong Park", "Harin J"],
    previewDate: "2026-03-24",
    startDate: "2026-03-25",
    endDate: "2026-03-29",
    status: "past",
    coverImage: "/art-fairs/artankara-2026/cover.jpg",
    description: "FOEM participated in ARTANKARA 2026, presenting works by Betty Moon, Uiyeong Park, and Harin J at Turkey's leading contemporary art fair.",
    artworkIds: ["w22", "w26", "w27", "w37", "w38", "w39", "w28", "w29"],
  },
  {
    id: "f8",
    name: "Seoul Art Show 2025",
    venue: "COEX",
    location: "Seoul, Korea",
    artists: ["Seong Eun Park"],
    previewDate: "2025-12-24",
    startDate: "2025-12-24",
    endDate: "2025-12-28",
    status: "past",
    coverImage: "/art-fairs/seoul-art-show-2025/seoul art show 2025.jpg",
  },
  {
    id: "f6",
    name: "AQUA Art Miami 2025",
    venue: "Aqua Hotel",
    location: "Miami Beach, FL",
    artists: ["Uiyeong Park"],
    startDate: "2025-12-03",
    endDate: "2025-12-07",
    status: "past",
    coverImage: "/art-fairs/aqua-art-miami-2025/aqua art miami 2025.jpg",
  },
];

export type Exhibition = {
  id: string;
  title: string;
  titleEn?: string;
  artists: string[];
  venue?: string;
  location: string;
  startDate: string;
  endDate: string;
  status: "current" | "upcoming" | "past";
  coverImage: string;
  heroImage?: string;
  description?: string;
  descriptionKo?: string;
  videoUrl?: string;
  orientation?: 'portrait' | 'landscape' | 'square';
  photos?: Array<{
    src: string;
    caption?: string;
    captionKo?: string;
    orientation?: 'portrait' | 'landscape' | 'square';
  }>;
};

export const exhibitions: Exhibition[] = [
  {
    id: "e10",
    title: 'bettymoon photographs "beyond the frame"',
    artists: ["Betty Moon"],
    location: "Seoul, Korea",
    startDate: "2026-06-08",
    endDate: "2026-06-18",
    status: "past",
    coverImage: "/exhibitions/beyond-the-frame-2026/beyond-the-frame.jpg",
    orientation: "portrait",
  },
  {
    id: "e11",
    title: "빛, 그림을 그리다",
    titleEn: "Painting with Light",
    artists: ["Betty Moon", "Ha Jeong Lim"],
    venue: "수원시립만석미술관 2층, 3전시장",
    location: "수원, 한국",
    startDate: "2026-05-26",
    endDate: "2026-05-31",
    status: "past",
    coverImage: "/exhibitions/bit-geurim-2026/poster.png",
    orientation: "portrait",
    description: "The light that illuminates the world\nis reborn at the fingertips of two artists.\n\nPhotography that captures a fleeting moment of light\nand holds it forever within a frame,\nand glass that transmits light itself,\ncreating brilliant variations.\n\nThe record of light projected through a camera lens\nand the transparent breath earned by glass enduring intense heat —\ntheir harmony stains the gallery walls and floor\ninto one vast canvas.\n\nIn this place where flat and three-dimensional,\nfrozen moments and moving shadows intersect,\nwe invite you to discover your own light.\n\nWhere a fleeting gaze meets lustrous texture —\ntoday, they paint a picture with light.",
    descriptionKo: "세상을 비추는 빛이\n두 예술가의 손끝에서 다시 태어납니다.\n\n찰나의 빛을 붙잡아 프레임 속에\n영원히 가둔 사진,\n그리고 스스로 빛을 투과하며\n찬란한 변주를 만들어내는 유리.\n\n카메라 렌즈를 통해 투영된 빛의 기록과\n뜨거운 열기를 견디며 투명한 숨결을 얻은 유리의 조화는\n전시장 벽면과 바닥을\n하나의 거대한 캔버스로 물들입니다.\n\n평면과 입체,\n정지된 순간과 움직이는 그림자가 교차하는 이곳에서\n당신만의 빛을 발견하는 시간을 가져보시길 바랍니다.\n\n찰나의 시선과 영롱한 질감이 만나,\n오늘 우리 앞에 빛으로 그림을 그립니다.",
    photos: [
      {
        src: "/exhibitions/bit-geurim-2026/betty-main-artwork.jpeg",
        orientation: "landscape",
      },
      {
        src: "/exhibitions/bit-geurim-2026/betty-photo.jpeg",
        orientation: "landscape",
        caption: "Installation view, Betty Moon. Moments where light paused and held still.",
        captionKo: "Betty Moon 섹션 전시 전경. 빛이 머문 순간의 기록들이 흰 벽 위에 나란히 걸렸다.",
      },
      {
        src: "/exhibitions/bit-geurim-2026/betty-photo.2.jpeg",
        orientation: "landscape",
        caption: "Where the two artists' worlds meet — Betty Moon's photographs and Ha Jeong Lim's glass in dialogue.",
        captionKo: "두 작가의 공간이 교차하는 지점. 사진 너머로 Ha Jeong Lim의 유리 작품이 공간을 투명하게 가로지른다.",
      },
      {
        src: "/exhibitions/bit-geurim-2026/lim-main-artwork.jpeg",
        orientation: "landscape",
      },
      {
        src: "/exhibitions/bit-geurim-2026/lim-glass-photo.jpeg",
        orientation: "landscape",
        caption: "Installation view, Ha Jeong Lim. Colored glass and steel wire compose their rhythm across the gallery wall.",
        captionKo: "Ha Jeong Lim 섹션 전시 전경. 색유리와 철선이 벽면을 캔버스 삼아 리듬을 그린다.",
      },
      {
        src: "/exhibitions/bit-geurim-2026/lim-glass-photo3.jpeg",
        orientation: "landscape",
        caption: "Corner installation view, Ha Jeong Lim. Glass that breathes with light, transforming the space around it.",
        captionKo: "Ha Jeong Lim 코너 설치 전경. 빛을 투과하는 유리가 공간 속에서 살아 숨쉰다.",
      },
    ],
  },
  {
    id: "e1",
    title: "Field of Emotions — Group Exhibition",
    artists: ["Betty Moon", "Uiyeong Park", "Harin J"],
    venue: "FOEM Gallery",
    location: "Seoul, Korea",
    startDate: "2026-04-15",
    endDate: "2026-06-01",
    status: "past",
    coverImage: "/exhibitions/field-of-emotions-2026/cover.jpg",
    description: "A group exhibition exploring the intersection of emotion and material form across photography and painting.",
  },
  {
    id: "e7",
    title: "T.I.D.E — From 0 to 25: Erasing Boundaries, 25 Perspectives",
    artists: ["Betty Moon", "Uiyeong Park", "Seong Eun Park", "Harin J", "Byeong-gwan Seo", "Jae Eun Jeong", "Young Jae Lee", "Insue Kim"],
    venue: "수원시 만석전시관 제1전시실",
    location: "Suwon, Korea",
    startDate: "2026-03-02",
    endDate: "2026-03-09",
    status: "past",
    coverImage: "/exhibitions/tide-2026/from0to25.jpg",
    description: "25명의 작가가 사진, 조각, 회화 세 장르를 넘나드는 그룹전. 각자의 시선이 모여 새로운 흐름을 만듭니다.",
    videoUrl: "https://www.instagram.com/p/DVXjZGXCaNg/",
  },
  {
    id: "e8",
    title: "T.I.D.E X Abijou: Beauty in Our Mind",
    artists: ["Betty Moon", "Uiyeong Park", "Seong Eun Park", "Harin J", "Byeong-gwan Seo", "Jae Eun Jeong", "Young Jae Lee", "Insue Kim"],
    venue: "Noblesse Collection",
    location: "Seoul, Korea",
    startDate: "2025-12-03",
    endDate: "2025-12-09",
    status: "past",
    coverImage: "/exhibitions/tide-x-abijou-2025/T.I.D.E X Abijou- Beauty in Our Mind.jpg",
    description: "T.I.D.E와 Abijou의 협업 전시. '-다움(美, 自, 人)'을 키워드로 획일화된 미의 기준에 의문을 던지며, 다양한 언어와 문화적 배경을 가진 작가들이 각자의 서사로 정체성과 감정을 풀어냅니다.",
    videoUrl: "https://www.instagram.com/p/DR4LRVeCQus/",
  },
  {
    id: "e9",
    title: "Beyond the Mirror — 본질을 향하여",
    artists: ["Betty Moon", "Uiyeong Park", "Seong Eun Park", "Harin J", "Byeong-gwan Seo", "Jae Eun Jeong", "Young Jae Lee", "Insue Kim"],
    venue: "Gallery ArtewIth",
    location: "Seoul, Korea",
    startDate: "2025-11-05",
    endDate: "2025-11-12",
    status: "past",
    coverImage: "/exhibitions/beyond-the-mirror-2025/beyond the mirror.jpg",
    description: "T.I.D.E 기획 그룹전. 25개의 시선이 모여 경계를 넘어 새로운 흐름을 만드는 순간.",
    videoUrl: "https://www.instagram.com/p/DQrhF6lCb9r/",
  },
  {
    id: "e5",
    title: "Layered Light",
    artists: ["Harin J"],
    venue: "FOEM Gallery",
    location: "Seoul, Korea",
    startDate: "2025-11-01",
    endDate: "2026-01-15",
    status: "past",
    coverImage: "/exhibitions/layered-light-2025/cover.jpg",
    description: "Harin J's debut solo exhibition at FOEM Gallery, tracing the boundary between memory and perception through layered painting.",
  },
  {
    id: "e6",
    title: "Golden Ground",
    artists: ["Sung Eun Park", "Betty Moon"],
    venue: "Gallery Hyundai",
    location: "Seoul, Korea",
    startDate: "2025-06-10",
    endDate: "2025-08-20",
    status: "past",
    coverImage: "/exhibitions/golden-ground-2025/cover.jpg",
    description: "A dialogue between traditional Korean pigment work and contemporary photography.",
  },
  {
    id: "e4",
    title: "Mother Nature 2024",
    artists: ["Betty Moon"],
    venue: "Seoul, Korea",
    location: "Seoul, Korea",
    startDate: "2024-10-01",
    endDate: "2024-11-30",
    status: "past",
    coverImage: "/exhibitions/mother-nature-2024/mother nature 2024.jpg",
    description: "Betty Moon's solo exhibition presenting large-scale archival pigment prints that trace the boundary between the human body and the natural world.",
  },
];

export function getArtworksByArtist(artistId: string) {
  return artworks.filter((a) => a.artistId === artistId);
}

export function getArtworksByCategory(category: Artwork["category"]) {
  return artworks.filter((a) => a.category === category);
}

export function getArtistBySlug(slug: string) {
  return artists.find((a) => a.slug === slug);
}

export function getVideosByArtist(artistId: string) {
  return artistVideos.filter((v) => v.artistId === artistId);
}

export function getArtworkById(id: string) {
  return artworks.find((a) => a.id === id);
}

export function formatPrice(price: number, locale = "ko") {
  if (locale === "ko") {
    return price.toLocaleString("ko-KR") + "원";
  }
  return "₩" + price.toLocaleString("ko-KR");
}
